spring.datasource.url=jdbc:postgresql://localhost:5432/stockup

spring.datasource.username=postgres

spring.datasource.password=dp123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=SUA_SENHA_DE_APP

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=sua_chave_secreta_super_longa_e_chave_criptografica_forte
jwt.expiration=86400000
